
<PhysicsWidget>:

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1

        Rectangle:
            pos: self.pos
            size: self.size


    PhysicsGame:
        id: game

        size: root.size
        pos: 0, 0


    AnchorLayout:
        id: toolbox_revealer

        pos: root.pos
        size: root.size
        padding: 10
        anchor_x: "left"
        anchor_y: "top"

        ToolBox:
            size_hint: (None, None)
            pos_hint: (None, None) 
